exception `InferException`
============================
__Package :__  `optima_v2.runtime`  
__Extends :__ [`Exception`](exception.md)

`InferException` represents an exception thrown when the runtime detected a fault while running inference.

This exception is thrown by the runtime in C++. On Python, users cannot create nor raise this exception.
